### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by KNIF** [anon5465984/KoiVM-Devirtualizer-ZIP#1]
Send password pls thx

**Comment by KNIF** [comment]
Some ppl already cracked the pwd, so pls share it with everyone else.

**Comment by Biggie7** [comment]
you can't crack Winrar encryption AES algorithm.

![](https://pix.watch/t6ylZv/ZXReTU.png)

i didn't crack the pass just guessed it because im close to pc-ret

**Comment by FinGu** [comment]
Show the files size

**Comment by KNIF** [comment]
oof
